### Create Song 
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "New song3",
    "artists": [2],
    "releasedDate" : "2023-03-11",
    "duration" :"02:33",
    "lyrics": "1adas adsdasd asdasdasd qeqew"
}

### home
GET http://localhost:3000

### Find all songs
GET http://localhost:3000/songs?page=1&limit=3


### Find one song
GET http://localhost:3000/songs/2

### Update Song
PUT http://localhost:3000/songs/2
 Content-Type: application/json

{
     "title": "You for Me 3",
     "artists": ["Siagla", "Yan", "Ny"],
     "releasedDate": "2022-09-30",
     "duration": "02:45",
     "lyrics": "Sby, you're my adrenaline. Brought out this other side of me You don't even know Controlling my whole anatomy, oh Fingers are holding you right at the edge You're slipping out of my hands Keeping my secrets all up in my head I'm"
}

### Delete Song
DELETE http://localhost:3000/songs/6481793569b739d7236e73b3

### Create playlist
POST http://localhost:3000/playlists
 Content-Type: application/json

{
    "name": "Feel Good Now",
    "songs": [6],
    "user": 3
}

### Signup User
POST http://localhost:3000/auth/signup
 Content-Type: application/json

{
    "firstName": "john",
    "lastName": "doe",
    "email": "john@gmail.com",
    "password": "123456"
}